### ISSUE TITLE
Having trouble 

### ISSUE THREAD

**Issue by Healsgoodman** [CardinalCyn/OctoCam#1]
I am using the windows exe file, and ive been able to get my snapshot to work fine but when i try to use my stream one it will not load it gives me the broken picture ill have attatched in the file. Any ideas :(? yawcam fails for me constantly and this looks really promising
![Screenshot 2023-06-13 201548](https://github.com/CardinalCyn/OctoCam/assets/136539822/08f32a2a-8e89-4b6b-9e8e-1eb575a4102f)

**Comment by CardinalCyn** [comment]
What happens when you put your the stream/snapshot urls into your browser?

**Comment by michaelcrossland1979** [comment]
Why he getting that is because most likely is due to the fact he is running it on a Pi or other computer inside his network and due the fact you using 127.0.0.1 as the base for the URLs that tells whatever is trying to look at that feed to be trying to look for the feed on there own device not the computer your running it on. Easy way to fix that change it so that it grabs the IP address that is handed out to the computer when joins the network and boom you can get it from all the computers on your network if you open those ports up in your windows firewall.

**Comment by CardinalCyn** [comment]
Take a look at the latest release, it should resolve this
