### ISSUE TITLE
Local network access 

### ISSUE THREAD

**Issue by Sanjay2802** [CardinalCyn/OctoCam#3]
How to access the link in local network??

**Comment by CardinalCyn** [comment]
Post it in your browser

**Comment by michaelcrossland1979** [comment]
You can't because the IP the program is hard coded to is the loopback IP meaning that any other computer or tab or phone tries to look at that URL feed they get zip, because you most like don't have anything running on those ports and if your on a mobil platform you should never have anything on those ports unless you did yourself.

**Comment by CardinalCyn** [comment]
Take a look at the latest release, it should resolve problems you have with running it on a local network.
