### ISSUE TITLE
Accessing feed from octoprint or mobile app throws an error and breaks feed

### ISSUE THREAD

**Issue by trevors1223** [CardinalCyn/OctoCam#4]
Below is the error i receive when accessing feed from octoprint locally or from the mobile app. 

127.0.0.1 - - [21/Jan/2024 23:23:01] "GET /stream/0/1920/1080 HTTP/1.1" 200 -
[ WARN:143@1031.887] global cap_msmf.cpp:471 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:143@1031.890] global cap_msmf.cpp:483 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
127.0.0.1 - - [21/Jan/2024 23:23:06] "GET /snapshot/0/1920/1080 HTTP/1.1" 200 -
[ WARN:142@1032.022] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072873821

**Comment by michaelcrossland1979** [comment]
That's because as of right now he has the program hard coded to use only the local computer loopback IP address meaning no other software can talk to his software unless it's running from the same computer as his software is running on. SO even if fyou were to move everything to a windows box. You still would not be able to get the video feed from any other computer then the one the software is running on. I have asked if he could redo that so that his program would pull the network facing IP that handed out when it joins the network and use that IP instead of the loopback one because like I said the loopback one only work for that computer and only it. Any other computers try to check that IP they are trying to take to their own sell's and they will never get anything unless you happen to have something running on those ports.
